#!/bin/bash

# Product Thinking Studio - Setup & Installation Guide

echo "╔══════════════════════════════════════════════════════════════╗"
echo "║                                                              ║"
echo "║          🚀  PRODUCT THINKING STUDIO  🚀                     ║"
echo "║                                                              ║"
echo "║     Professional AI-Powered Product Decision Framework      ║"
echo "║                                                              ║"
echo "╚══════════════════════════════════════════════════════════════╝"
echo ""
echo "📋 PREREQUISITES"
echo "   ✓ Python 3.8 or higher"
echo "   ✓ OpenAI API key"
echo "   ✓ Internet connection"
echo ""
echo "📦 INSTALLATION STEPS"
echo ""
echo "1️⃣  Create a virtual environment (recommended)"
echo "   $ python3 -m venv venv"
echo "   $ source venv/bin/activate  # On Windows: venv\\Scripts\\activate"
echo ""
echo "2️⃣  Install dependencies"
echo "   $ pip install -r requirements.txt"
echo ""
echo "3️⃣  Set up environment variables"
echo "   $ cp .env.example .env"
echo "   $ nano .env  # Add your OPENAI_API_KEY"
echo ""
echo "4️⃣  Run the application"
echo "   $ streamlit run app/app.py"
echo "   OR"
echo "   $ ./run.sh"
echo ""
echo "5️⃣  Open in browser"
echo "   🌐 http://localhost:8501"
echo ""
echo "╔══════════════════════════════════════════════════════════════╗"
echo "║  QUICK START                                                 ║"
echo "╚══════════════════════════════════════════════════════════════╝"
echo ""
echo "   Just run: ./run.sh"
echo ""
echo "   The script will:"
echo "   • Create virtual environment (if needed)"
echo "   • Install all dependencies"
echo "   • Launch the application"
echo "   • Open in your default browser"
echo ""
echo "╔══════════════════════════════════════════════════════════════╗"
echo "║  FEATURES                                                    ║"
echo "╚══════════════════════════════════════════════════════════════╝"
echo ""
echo "   ✨ Beautiful, professional UI with animations"
echo "   🧠 AI-powered product thinking analysis"
echo "   📊 Comprehensive decision framework"
echo "   ⚠️  Multi-dimensional risk assessment"
echo "   🎯 Actionable next steps"
echo "   📈 Success metrics identification"
echo ""
echo "╔══════════════════════════════════════════════════════════════╗"
echo "║  SUPPORT                                                     ║"
echo "╚══════════════════════════════════════════════════════════════╝"
echo ""
echo "   📖 Documentation: README.md"
echo "   🎨 UI/UX Guide: docs/ui-ux-features.md"
echo "   📝 Decision Log: docs/product-decisions.md"
echo ""
echo "   Built with ❤️  for Product Managers"
echo ""
